"""empty message

Revision ID: 13f0f8877082
Revises: f2d4c985e327
Create Date: 2020-09-16 00:47:40.892011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f0f8877082'
down_revision = 'f2d4c985e327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('reservations', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'reservations', ['end_time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='unique')
    op.drop_column('reservations', 'end_time')
    op.drop_table('reviews')
    # ### end Alembic commands ###
