"""empty message

Revision ID: 1ddea8863969
Revises: b2ddfee6996d
Create Date: 2020-09-23 18:38:41.278383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ddea8863969'
down_revision = 'b2ddfee6996d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sports', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.drop_column('users', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('genres', postgresql.ARRAY(sa.VARCHAR(length=120)), autoincrement=False, nullable=True))
    op.drop_column('users', 'sports')
    # ### end Alembic commands ###
