"""empty message

Revision ID: 2900afef144c
Revises: ee2f9fe76f45
Create Date: 2020-10-01 00:31:09.281649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2900afef144c'
down_revision = 'ee2f9fe76f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('status', sa.Boolean(), nullable=False))
    op.add_column('reviews', sa.Column('trainer_id', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'user_id')
    op.drop_column('reviews', 'trainer_id')
    op.drop_column('reviews', 'status')
    # ### end Alembic commands ###
