"""empty message

Revision ID: 504b7f0927ea
Revises: 5cfe1ff51258
Create Date: 2020-09-08 19:04:58.971323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504b7f0927ea'
down_revision = '5cfe1ff51258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('trainer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reservations', 'trainees', ['trainer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_column('reservations', 'trainer_id')
    # ### end Alembic commands ###
