"""empty message

Revision ID: 5a7b7af65d69
Revises: 2900afef144c
Create Date: 2020-10-02 19:08:03.708295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7b7af65d69'
down_revision = '2900afef144c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
