"""empty message

Revision ID: 6858215c9be6
Revises: 493acc33779c
Create Date: 2020-09-07 15:07:28.405664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6858215c9be6'
down_revision = '493acc33779c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainees', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('trainees', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainees', 'price')
    op.drop_column('trainees', 'bio')
    # ### end Alembic commands ###
