"""empty message

Revision ID: aa16b5d99ed4
Revises: 
Create Date: 2020-10-05 17:00:37.890674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa16b5d99ed4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('status', sa.Boolean(), nullable=False))
    op.add_column('reviews', sa.Column('trainer_id', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'user_id')
    op.drop_column('reviews', 'trainer_id')
    op.drop_column('reviews', 'status')
    # ### end Alembic commands ###
