"""empty message

Revision ID: b9b6486df36b
Revises: eaa721387194
Create Date: 2020-09-08 19:09:07.370630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b6486df36b'
down_revision = 'eaa721387194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reservations', ['start_time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='unique')
    # ### end Alembic commands ###
